version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hNPpVVoVuz9YrtVyJlyC7YQI5WoQshfgF8IqEllnRZk"
            - "81:c7:09:20:03:fc:93:db:1e:5b:a5:4b:e3:55:24:81"
      - checkout
      - run: yarn
      - run: yarn build
      - run: scp -r build/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
  # deploy:
  #   machine:
  #     enabled: true
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8"
  #           - "81:c7:09:20:03:fc:93:db:1e:5b:a5:4b:e3:55:24:81"
  #     - run:
  #         name: "Deploy Over SSH"
  #         command: |
  #           scp -r react-game-life/build/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master