version: 2
jobs:
  build:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - run: yarn
      - run: yarn build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: "Deploy Over SSH"
          command: |
            scp -r build/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master