version: 2
jobs:
  build:
    steps:
      - run: yarn
      - run: yarn build
  deploy:
    steps:
      - run: scp -r build/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
    # machine:
    #   enabled: true
    #       name: "Deploy Over SSH"
    #       command: |
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master