name: Deploy to GH Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check it out 🕶
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 20.2.0
          
      - name: Build
        run: |
          npm ci
          npm run build
          
      - name: Publish
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          # Optional. Default value "." means the root directory of your project will be published.
          # You can use whatever directory your project uses, for example "wwwroot".
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically by your static website builder.
          source-directory: dist

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will OVERWRITE this branch.
          target-branch: gh-pages
